name: Compilação do kernel Linux TkG
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Liberação de espaço em disco
#        run: |
#          df -h
#          sudo apt autoremove --purge -y azure-cli '^dotnet-.*' firefox google-chrome-stable google-cloud-sdk hhvm '^llvm-.*' powershell snapd
#          sudo apt clean
#          sudo swapoff -a
#          sudo rm -rf "$AGENT_TOOLSDIRECTORY" /opt/az /swapfile /usr/share/dotnet /usr/local/share/boost
#          df -h
      - name: Execução do script de compilação
        run: |
          ls -la /home/runner/work/linux-tkg-rauldipeas/linux-tkg-rauldipeas
          mkdir -pv /home/runner/work/linux-tkg-rauldipeas/linux-tkg-rauldipeas/linux-tkg/DEBS
          cd /home/runner/work/linux-tkg-rauldipeas/linux-tkg-rauldipeas/linux-tkg/DEBS/
          wget -c https://go.skype.com/skypeforlinux-64.deb
#        run: bash ./linux-tkg-build.sh
      - name: Upload dos pacotes para o lançamento
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          args: /home/runner/work/linux-tkg-rauldipeas/linux-tkg-rauldipeas/linux-tkg/DEBS/*